#!/bin/bash
echo-title() {
    local text="$2"
    local format="$1"
    local columns=$(tput cols)
    local padding=$(( (columns - ${#text}) / 2 ))
    printf "%*s%s\n" $padding "" "$format$text$normal"
}

printf "\n\n\n"
echo-title "$(tput setaf 150 bold)" "( O ⁠ω ⁠O )"
echo-title "$(tput setaf 150 bold)" "welcome!"
printf "\n\n"

printf "A shortcut to compile c++ code into hex-file for microbit."
printf "$(tput bold)Please, ensure, that you have moved to your project's directory have added the build-command in the arguements.$(tput sgr0)\n"

docker run -v $(pwd):/home --rm ghcr.io/carlosperate/microbit-toolchain:latest "$@"

notify-send "Process complete :³"
printf "\n"
echo-title "$(tput setaf 150 bold)" "PROCESS COMPLETE"
