#!/bin/bash

normal=$(tput sgr0)

echo-title() {
    local text="$2"
    local format="$1"
    local columns=$(tput cols)
    local padding=$(( (columns - ${#text}) / 2 ))
    printf "%*s%s\n" $padding "" "$format$text$normal"
}

printf "\n\n\n"
echo-title "$(tput setaf 150 bold)" "( O ⁠ω ⁠O )"

printf "A shortcut to compile c++ code into hex-file for microbit. Please, ensure, that you have moved to your project's directory have added the build-command in the arguements.\n"

docker run -v $(pwd):/home --rm ghcr.io/carlosperate/microbit-toolchain:latest "$@"

# notify-send "Process complete"
printf "\n"
echo-title "$(tput setaf 150 bold)" "PROCESS COMPLETE"
